### PR TITLE
Modern Design -  New Icon - Pulldown to refresh

### PR DESCRIPTION
**Pull request by L1am0**
1) I created a new style file for v22+ to provide the users with an modern feeling UI.
2) Added a Pulldown to refresh feature. Just pull down the main activity and the currencys get updated
3) New Icon for the App to fit the new Layout

### CODE REVIEW

**Comment by billthefarmer** [comment]
OK, I will test this.

**Comment by billthefarmer** [comment]
Compilation fails on lint checks...

  | Correctness
-- | --
6 | error MergeMarker: Code contains merge marker
1 | warning OldTargetApi: Target SDK attribute is not targeting latest version
12 | error AppCompatResource: Menu namespace
1 | warning GradleDependency: Obsolete Gradle Dependency
1 | warning GradleOverrides: Value overridden by Gradle build script
  | Usability:Icons
1 | warning IconDipSize: Icon density-independent size validation
  | Disabled Checks (22)

**Comment by L1am0** [comment]
Could you please help me: What are the lint checks? Do I have to enable them in android studio?
When I build the project it worked and I was able to run it on my phone.

**Comment by billthefarmer** [comment]
I don't use Android Studio, just Gradle. There should be the same lint checks because it's part of the Gradle build command. You can do the lint checks from the command line with `gradle lint` or ./gradlew lint`  or `gradlew.bat lint` depending on operating system and whether you have Gradle installed.

**Pull request closed without merging**
