### PR TITLE
Updated it (Italian) translation

### PR DESCRIPTION
**Pull request by IZ2QDH**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by billthefarmer** [comment]
Well that's seriously weird. Stringlate seems to have created a [new branch](https://github.com/IZ2QDH/currency/tree/stringlate-it-1963) from an old commit dating back to Jan 2017. Don't worry about that, I'll fix it my end and this will get merged.

**Comment by IZ2QDH** [comment]
Ok, it's the first time i use Stringlate so i don't know if i did something wrong

**Comment by billthefarmer** [comment]
I've reported an [issue](https://github.com/LonamiWebs/Stringlate/issues/286) to Stringlate. I've had problems before with this app trying to be too clever and breaking things. As a user, IMHO,  you shouldn't be able to do something as weird as that.

**Comment by billthefarmer** [comment]
OK, thank you. I have added that. It hasn't picked it up here because I used devious methods. Some of the strings were missing, so I added them with Google Translate which might have got it right, possibly not.

**Comment by IZ2QDH** [comment]
If i find something strange in the translation i'll correct it

**Pull request closed without merging**
